# Generated by Django 2.0.2 on 2018-03-05 01:40

from django.db import migrations, models
import modules.status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180305_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=modules.status.models.upload_status_image),
        ),
    ]
